# Generated by Django 4.2 on 2023-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_solddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solddate',
            name='date',
            field=models.DateField(verbose_name='Sold Date'),
        ),
    ]
